# Generated by Django 4.0.5 on 2022-06-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_username', models.CharField(max_length=255)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_username', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=100)),
                ('user_phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
